Addressed some errors when compiling under Neutron_Clang-17
1- techpack:display: fix type specifier missing
../techpack/display/msm/sde/sde_hw_dsc_1_2.c:80:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static inline _dsc_subblk_offset(struct sde_hw_dsc *hw_dsc, int s_id,
~~~~~~~~~~~~~ ^
int
1 error generated.
Signed-off-by: klozz <carlosj@klozz.dev>

2- qcacld-3.0: Fix compilation with Snapdragon Clang 16.0.2
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:5914:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[SIR_MDIE_SIZE])
                           ^
../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1028:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
                   uint8_t mdie[]);

3- msm: ipa_v2: Fix filter enum mismatch and ip_type conversion
- clang 16 warning:

../drivers/platform/msm/ipa/ipa_v2/rmnet_ipa.c:442:34: warning: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Wenum-conversion]
                        rule_req->filter_spec_list[i].ip_type;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../drivers/platform/msm/ipa/ipa_v2/rmnet_ipa.c:444:34: warning: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Wenum-conversion]
                        rule_req->filter_spec_list[i].filter_action;
Change-Id: 41a60a2fe4bd6f46af8bacc6012c65be7c02ab0b
Signed-off-by: TogoFire <italomellopereira@gmail.com>
Signed-off-by: mcdofrenchfreis <xyzevan@androidist.net>

	modified:   drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h
	modified:   drivers/usb/misc/usbdtp.c
	modified:   net/ipv4/tcp_timer.c
	modified:   techpack/display/msm/sde/sde_hw_dsc_1_2.c
	modified:   techpack/display/msm/sde/sde_hw_vdc.c